# Generated by Django 4.2.16 on 2026-06-04 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('programming', 'Programming'), ('data_science', 'Data Science'), ('design', 'Design'), ('business', 'Business'), ('marketing', 'Marketing'), ('other', 'Other')], default='other', max_length=50)),
                ('duration', models.CharField(help_text='e.g., 4 weeks, 10 hours', max_length=100)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.mentor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
