version: "3.9"

services:

  backend:
    build: ./mentorship_platform
    container_name: backend

    env_file:
      - ./mentorship_platform/.env

    ports:
      - "8000:8000"

    restart: unless-stopped

    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend

    ports:
      - "3000:3000"

    depends_on:
      - backend

    restart: unless-stopped

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
