name: Frontend CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test

      - name: Build
        run: npm run build
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: validate dockerfile
        run: docker buildx build --check .
        
      - name: build docker image 
        run: docker buildx build --load -t mvp-frontend:test .
        
      - name: Run frontend container
        run: docker run -d --name frontend -p 8080:80 mvp-frontend:test

      - name: Smoke test
        run: curl --fail http://localhost:8080